# Generated by Django 4.1.6 on 2023-02-07 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BID', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('author', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('alias', models.CharField(max_length=256)),
                ('is_food', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RID', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('persons', models.IntegerField(default=2)),
                ('page', models.IntegerField()),
                ('preparation', models.IntegerField(blank=True, help_text='preparation time in minutes', null=True)),
                ('cooking', models.IntegerField(blank=True, help_text='cooking time in minutes', null=True)),
                ('energy', models.IntegerField(blank=True, help_text='total energy required in KWH', null=True)),
                ('soak', models.IntegerField(blank=True, help_text='soak time in minutes', null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.book')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('plural', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.ingredient')),
                ('qualifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.qualifier')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.recipe')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.unit')),
            ],
        ),
    ]
